Wp qspi boot 2021 1
Avnet/meta-avnet pull request #36
Opened 2021-10-19 18:19 UTC by wpatterson-witekio

The minimal image has grow too big to fit in 16MB QSPI for minized, pz and mz. 

The major differences between 2020 and 2021 are:

- petalinux-image-common added several packages, the biggest being `meson` adding 18MB and htop adding 1MB. This is fixed by explicitly removing them from the minimal image
- linux is now configured to include a lot of media related modules by default, adding another 1MB. This is fixed by explicitly unsetting media support

2021-10-25 19:52 UTC, narrucmot approved these changes

2021-10-26 00:29 UTC, AlbertaBeef approved these changes
Great find Will, agreed to remove the meson/htop packages for these small footprint targets.

2021-10-26 16:20 UTC, tnizan-witekio requested changes

2021-10-26 16:20 UTC, tnizan-witekio commented on recipes-core/images/avnet-image-minimal.inc
> +IMAGE_INSTALL_remove_minized-sbc = "\
As you remove htop and meson for minized, mz and pz, I think you can use instead: 
IMAGE_INSTALL_remove_zynq

2021-10-26 18:02 UTC, wpatterson-witekio commented on recipes-core/images/avnet-image-minimal.inc
> +IMAGE_INSTALL_remove_minized-sbc = "\
Good point, I just update, retested and pushed

2021-10-26 18:38 UTC, tnizan-witekio approved these changes

2021-10-26 18:39 UTC, merged